import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test-setup.ts'],
    globals: true,
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '__tests_unused/**',
      '**/*integration*.test.ts',
      '**/*Integration*.test.tsx',
      'quality-core/dashboard/node_modules/**',
      '_dev/**',
      '.bun/**',
      'tmp/**',
      'temp/**',
      'logs/**',
      'performance-reports/**',
      'docs/**',
      '.gemini/**',
      '.gemini-clipboard/**',
      '.cache/**',
      '.parcel-cache/**',
      '.vscode/**',
      '.idea/**',
      '.pnp',
      '.pnp.js',
      '.env',
      '.env.*',
      '*.log',
      'e2e/**',
      'quality-core/dashboard/**',
    ],
    coverage: {
      provider: 'v8',
      reportsDirectory: 'performance-reports/coverage',
      exclude: [
        '**/node_modules/**',
        '**/dist/**',
        '**/build/**',
        '__tests_unused/**',
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/test-setup.ts',
        'coverage/**',
        'logs/**',
        'performance-reports/**',
        'docs/**',
        'tmp/**',
        'temp/**',
        '.bun/**',
        '.gemini/**',
        '.gemini-clipboard/**',
        '.cache/**',
        '.parcel-cache/**',
        '.vscode/**',
        '.idea/**',
        '.pnp',
        '.pnp.js',
        '.env',
        '.env.*',
        '*.log',
        'config/**',
        'e2e/**',
        'C:*',
        'google-chrome-stable_current_amd64.deb',
        '**/*.config.ts',
        '**/*.config.js',
        '_dev/**',
        '**/eslint.config.*',
        'quality-core/dashboard/**',
      ]
    }
  }
});
