import type { UiGateReview } from "../ui-gate";

export const uiGateReviews: UiGateReview[] = [
  {
    artifactId: "promo-home",
    artifactKind: "promo-page",
    artifactLabel: "Promo Home",
    board: "marketing-page",
    notes: [
      "Hero limitado a titulo, apoio curto, tags, CTA e imagem unica.",
      "A home explica proposito e diferencas entre repo local, web e app.",
      "Nao ha CTA duplicado no mesmo viewport.",
    ],
    evidence: [
      "http://localhost:5173/#home",
      "http://localhost:4175/personalnews/#home",
    ],
    scores: {
      purpose: 9.2,
      typography: 9.1,
      consistency: 9.1,
      hierarchy: 9.1,
      layoutDiscipline: 9.0,
      wcag: 9.3,
    },
    criticalFlags: [],
  },
  {
    artifactId: "promo-experience",
    artifactKind: "promo-page",
    artifactLabel: "Promo Experience",
    board: "marketing-page",
    notes: [
      "A pagina mostra layouts por ilustracao e pouco texto.",
      "Customizacao e onboarding aparecem em secoes separadas, sem colunas competindo.",
    ],
    evidence: [
      "http://localhost:5173/#experience",
      "http://localhost:4175/personalnews/#experience",
    ],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.1,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.2,
    },
    criticalFlags: [],
  },
  {
    artifactId: "promo-project",
    artifactKind: "promo-page",
    artifactLabel: "Promo Project",
    board: "marketing-page",
    notes: [
      "Ordem fixa respeitada: tecnologia, qualidade, commits, outros projetos, sobre, footer.",
      "O sobre deixa claro que mafhper e o desenvolvedor do projeto.",
    ],
    evidence: [
      "http://localhost:5173/#project",
      "http://localhost:4175/personalnews/#project",
    ],
    scores: {
      purpose: 9.1,
      typography: 9.0,
      consistency: 9.1,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.2,
    },
    criticalFlags: [],
  },
  {
    artifactId: "promo-faq",
    artifactKind: "promo-page",
    artifactLabel: "Promo FAQ",
    board: "marketing-page",
    notes: [
      "FAQ cobre diferencas entre versoes, instalacao e problemas de feed/proxy/CORS.",
      "A estrutura reduz atrito no primeiro uso sem virar documentacao tecnica pesada.",
    ],
    evidence: [
      "http://localhost:5173/#faq",
      "http://localhost:4175/personalnews/#faq",
    ],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.2,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-modern",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Modern",
    board: "ui-release",
    notes: [
      "Layout validado como referencia principal do feed.",
      "Contraste e ritmo vertical alinhados ao contrato atual do feed.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.1,
      hierarchy: 9.0,
      layoutDiscipline: 9.1,
      wcag: 9.2,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-grid",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Grid",
    board: "ui-release",
    notes: [
      "Grid refinado para manter espacamento do header ate a pagina final.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.1,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-split",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Split",
    board: "ui-release",
    notes: [
      "Lead principal e coluna de apoio seguem hierarquia clara.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.1,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-magazine",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Magazine",
    board: "ui-release",
    notes: [
      "Magazine prioriza hierarquia editorial com contraste controlado.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.1,
      layoutDiscipline: 9.0,
      wcag: 9.1,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-minimal",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Minimal",
    board: "ui-release",
    notes: [
      "Layout minimal preserva metadata e titulos sem overlays ruidosos.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.1,
    },
    criticalFlags: [],
  },
  {
    artifactId: "feed-bento",
    artifactKind: "feed-layout",
    artifactLabel: "Feed Bento",
    board: "ui-release",
    notes: [
      "Bento ajustado com chip intrinseco e horario na mesma linha.",
    ],
    evidence: ["http://localhost:5173/#feed"],
    scores: {
      purpose: 9.0,
      typography: 9.0,
      consistency: 9.0,
      hierarchy: 9.0,
      layoutDiscipline: 9.0,
      wcag: 9.1,
    },
    criticalFlags: [],
  },
];
