import React, { createContext, useContext, useState, useEffect } from 'react';
import { useLocalStorage } from '../hooks/useLocalStorage';

export type Language = 'pt-BR' | 'en-US' | 'es' | 'fr' | 'it' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // General
    'app.title': 'Personal News',
    'loading': 'Carregando...', 
    'search.placeholder': 'Buscar artigos...',
    'search.results': 'Resultados para',
    'no.results': 'Nenhum resultado encontrado',
    'read.more': 'Ler mais',
    'published': 'Publicado em',
    'author': 'Por',
    'source': 'Fonte',
    
    // Actions
    'action.add': 'Adicionar',
    'action.cancel': 'Cancelar',
    'action.save': 'Salvar',
    'action.delete': 'Excluir',
    'action.edit': 'Editar',
    'action.refresh': 'Atualizar',
    'action.reset': 'Resetar',
    'action.close': 'Fechar',
    'action.back': 'Voltar',
    'action.import': 'Importar',
    'action.export': 'Exportar',
    'action.remove': 'Remover',
    'action.preview': 'Preview',
    'action.next': 'Próximo',
    'action.prev': 'Anterior',
    'action.focus_mode': 'Modo Foco',
    'action.read': 'Ler',
    'action.read_article': 'Ler artigo',
    
    // Time
    'time.now': 'agora',
    
    // Feeds extended
    'feeds.live': 'AO VIVO',
    'feeds.articles': 'artigos',
    
    // Article extended
    'article.by': 'por',
    'article.end': 'Fim da edição',
    
    // Header
    'header.manage_feeds': 'Gerenciar Feeds',
    'header.refresh': 'Atualizar Feeds',
    'header.settings': 'Configurações',
    'header.favorites': 'Favoritos',
    'header.menu': 'Menu',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.language': 'Idioma',
    'settings.tab.appearance': 'Aparência',
    'settings.tab.display': 'Exibição',
    'settings.tab.logs': 'Logs',
    'settings.tab.advanced': 'Avançado',
    
    // Settings - Appearance
    'settings.header.config': 'Configuração do Header',
    'settings.header.title': 'Título',
    'settings.header.logo': 'Logo URL',
    'settings.header.upload': 'Upload',
    'settings.header.position': 'Posição',
    'settings.header.height': 'Altura',
    'settings.header.theme_color': 'Cor do Tema',
    'settings.header.blur': 'Blur',
    'settings.layout.preset': 'Preset de Layout',
    'settings.colors': 'Cores',
    'settings.background': 'Fundo',
    
    // Settings - Display
    'settings.display.options': 'Opções de Exibição',
    'settings.display.top_stories': 'Top Stories',
    'settings.display.auto_refresh': 'Atualização Automática',
    'settings.display.time_format': 'Formato de Hora',
    'settings.display.show_time': 'Mostrar Horário',
    
    // Settings - Advanced
    'settings.system': 'Sistema',
    'settings.system.detect_theme': 'Detectar Tema',
    'settings.system.transitions': 'Transições Suaves',
    'settings.backup': 'Backup & Dados',
    'settings.backup.desc': 'Exporte seus dados para migrar de dispositivo',
    'settings.reset.factory': 'Reset de Fábrica',
    'settings.reset.desc': 'Restaura padrões visuais',
    
    // Feed Manager
    'feeds.title': 'Gerenciar Feeds',
    'feeds.tab.feeds': 'Feeds',
    'feeds.tab.categories': 'Categorias',
    'feeds.tab.analytics': 'Resumo',
    'feeds.add.placeholder': 'Digite a URL do site, feed RSS ou canal do YouTube...',
    'feeds.import.lists': 'Importar Listas',
    'feeds.import.opml': 'Importar OPML',
    'feeds.stats.monitored': 'feeds monitorados',
    'feeds.category.none': 'Sem categoria',
    'feeds.category.empty': 'Nenhum feed disponível',
    'feeds.category.pin': 'Fixar',
    'feeds.category.unpin': 'Desafixar',
    
    // Analytics
    'analytics.total_articles': 'Artigos em Cache',
    'analytics.updated': 'Atualizado',
    'analytics.health': 'Saúde do Sistema',
    'analytics.operational': '100% Operacional',
    'analytics.issues': 'com erro',
    'analytics.popular_topics': 'Assuntos Populares',
    'analytics.frequency': 'Maior Frequência',
    'analytics.feed_status': 'Status dos Feeds',
    'analytics.attention': 'Atenção Necessária',
    'analytics.valid': 'Válidos',
    'analytics.pending': 'Pendentes',
    
    // Layouts
    'layout.grid': 'Magazine',
    'layout.modern': 'Moderno',
    'layout.masonry': 'Masonry',
    'layout.list': 'Lista',
    'layout.minimal': 'Minimalista',
    'layout.immersive': 'Imersivo',
    'layout.timeline': 'Timeline',
    'layout.bento': 'Bento',
    'layout.brutalist': 'Brutalist',
    'layout.newspaper': 'Jornal',
    'layout.focus': 'Foco',
    'layout.gallery': 'Galeria',
    'layout.compact': 'Compacto',
    'layout.split': 'Split',
    'layout.cyberpunk': 'Cyberpunk',
    'layout.terminal': 'Terminal',
    'layout.pocketfeeds': 'PocketFeeds',
    'layout.default': 'Usar Padrão Global',

    // Customizer
    'customizer.title': 'Configurações de Aparência',
    'customizer.subtitle': 'Personalize layout, cores e estilo',
    'customizer.tab.layouts': 'Layouts',
    'customizer.tab.colors': 'Cores',
    'customizer.tab.header': 'Cabeçalho',
    'customizer.tab.content': 'Conteúdo',
    'customizer.tab.background': 'Fundo',
    'customizer.tab.import_export': 'Imp/Exp',
    'customizer.group.primary_colors': 'Cores Primárias',
    'customizer.group.background_colors': 'Cores de Fundo',
    'customizer.export.desc': 'Exporte seu tema atual para compartilhar ou fazer backup.',
    'customizer.import.desc': 'Importe um tema a partir de um JSON.',
    'customizer.import.placeholder': 'Cole o JSON do tema aqui...',
    
    // Article & Layout Specifics
    'article.read_full': 'Ler História Completa',
    'article.scroll_hint': 'Role ou Use Setas para Navegar',
    'article.vol': 'Vol.',
    'article.no': 'Nº',
    'weather.city_prompt': 'Digite o nome da cidade para a previsão do tempo:',
    
    // Feed Manager Extended
    'feeds.duplicate.title': 'Feed Duplicado Detectado',
    'feeds.duplicate.message': 'Este feed parece ser uma duplicata de um existente.',
    'feeds.duplicate.existing': 'Feed Existente',
    'feeds.duplicate.new': 'Novo Feed',
    'feeds.duplicate.confidence': 'Confiança da detecção',
    'feeds.action.cancel_dont_add': 'Cancelar - Não Adicionar',
    'feeds.action.replace': 'Substituir Existente',
    'feeds.action.add_anyway': 'Adicionar Mesmo Assim',
    'feeds.import_curated.title': 'Importar Feeds Curados',
    'feeds.import_curated.select': 'Selecionar Lista',
    'feeds.import_curated.merge': 'Mesclar (Adicionar)',
    'feeds.import_curated.replace': 'Substituir Todos',
  },
  'en-US': {
    'app.title': 'Personal News',
    'loading': 'Loading...', 
    'search.placeholder': 'Search articles...', 
    'search.results': 'Results for',
    'no.results': 'No results found',
    'read.more': 'Read more',
    'published': 'Published on',
    'author': 'By',
    'source': 'Source',
    'action.add': 'Add',
    'action.cancel': 'Cancel',
    'action.save': 'Save',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.refresh': 'Refresh',
    'action.reset': 'Reset',
    'action.close': 'Close',
    'action.back': 'Back',
    'action.import': 'Import',
    'action.export': 'Export',
    'action.remove': 'Remove',
    'action.preview': 'Preview',
    'action.next': 'Next',
    'action.prev': 'Prev',
    'action.focus_mode': 'Focus Mode',
    'action.read': 'Read',
    'action.read_article': 'Read article',
    
    // Time
    'time.now': 'now',
    
    // Feeds extended
    'feeds.live': 'LIVE',
    'feeds.articles': 'articles',
    
    // Article extended
    'article.by': 'by',
    'article.end': 'End of edition',
    
    // Header
    'header.refresh': 'Refresh Feeds',
    'header.settings': 'Settings',
    'header.favorites': 'Favorites',
    'header.menu': 'Menu',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.tab.appearance': 'Appearance',
    'settings.tab.display': 'Display',
    'settings.tab.logs': 'Logs',
    'settings.tab.advanced': 'Advanced',
    'settings.header.config': 'Header Configuration',
    'settings.header.title': 'Title',
    'settings.header.logo': 'Logo URL',
    'settings.header.upload': 'Upload',
    'settings.header.position': 'Position',
    'settings.header.height': 'Height',
    'settings.header.theme_color': 'Theme Color',
    'settings.header.blur': 'Blur',
    'settings.layout.preset': 'Layout Preset',
    'settings.colors': 'Colors',
    'settings.background': 'Background',
    'settings.display.options': 'Display Options',
    'settings.display.top_stories': 'Top Stories',
    'settings.display.auto_refresh': 'Auto Refresh',
    'settings.display.time_format': 'Time Format',
    'settings.display.show_time': 'Show Time',
    'settings.system': 'System',
    'settings.system.detect_theme': 'Auto Theme',
    'settings.system.transitions': 'Smooth Transitions',
    'settings.backup': 'Backup & Data',
    'settings.backup.desc': 'Export data to migrate devices',
    'settings.reset.factory': 'Factory Reset',
    'settings.reset.desc': 'Restore visual defaults',
    'feeds.title': 'Manage Feeds',
    'feeds.tab.feeds': 'Feeds',
    'feeds.tab.categories': 'Categories',
    'feeds.tab.analytics': 'Analytics',
    'feeds.add.placeholder': 'Enter website URL, RSS feed or YouTube channel...', 
    'feeds.import.lists': 'Import Lists',
    'feeds.import.opml': 'Import OPML',
    'feeds.stats.monitored': 'monitored feeds',
    'feeds.category.none': 'Uncategorized',
    'feeds.category.empty': 'No feeds available',
    'feeds.category.pin': 'Pin',
    'feeds.category.unpin': 'Unpin',
    'analytics.total_articles': 'Cached Articles',
    'analytics.updated': 'Updated',
    'analytics.health': 'System Health',
    'analytics.operational': '100% Operational',
    'analytics.issues': 'issues',
    'analytics.popular_topics': 'Popular Topics',
    'analytics.frequency': 'Top Frequency',
    'analytics.feed_status': 'Feed Status',
    'analytics.attention': 'Needs Attention',
    'analytics.valid': 'Valid',
    'analytics.pending': 'Pending',
    'layout.grid': 'Magazine',
    'layout.modern': 'Modern',
    'layout.masonry': 'Masonry',
    'layout.list': 'List',
    'layout.minimal': 'Minimal',
    'layout.immersive': 'Immersive',
    'layout.timeline': 'Timeline',
    'layout.bento': 'Bento',
    'layout.brutalist': 'Brutalist',
    'layout.newspaper': 'Newspaper',
    'layout.focus': 'Focus',
    'layout.gallery': 'Gallery',
    'layout.compact': 'Compact',
    'layout.split': 'Split',
    'layout.cyberpunk': 'Cyberpunk',
    'layout.terminal': 'Terminal',
    'layout.pocketfeeds': 'PocketFeeds',
    'layout.default': 'Use Global Default',

    // Customizer
    'customizer.title': 'Appearance Settings',
    'customizer.subtitle': 'Customize layout, colors, and style',
    'customizer.tab.layouts': 'Layouts',
    'customizer.tab.colors': 'Colors',
    'customizer.tab.header': 'Header',
    'customizer.tab.content': 'Content',
    'customizer.tab.background': 'Background',
    'customizer.tab.import_export': 'Imp/Exp',
    'customizer.group.primary_colors': 'Primary Colors',
    'customizer.group.background_colors': 'Background Colors',
    'customizer.export.desc': 'Export your current theme to share with others or backup your customizations.',
    'customizer.import.desc': 'Import a theme from JSON data.',
    'customizer.import.placeholder': 'Paste Theme JSON here...',

    // Article & Layout Specifics
    'article.read_full': 'Read Full Story',
    'article.scroll_hint': 'Scroll / Arrows to Navigate',
    'article.vol': 'Vol.',
    'article.no': 'No.',
    'weather.city_prompt': 'Enter city name for weather forecast:',

    // Feed Manager Extended
    'feeds.duplicate.title': 'Duplicate Feed Detected',
    'feeds.duplicate.message': 'This feed appears to be a duplicate of an existing one.',
    'feeds.duplicate.existing': 'Existing Feed',
    'feeds.duplicate.new': 'New Feed',
    'feeds.duplicate.confidence': 'Detection confidence',
    'feeds.action.cancel_dont_add': 'Cancel - Don\'t Add',
    'feeds.action.replace': 'Replace Existing',
    'feeds.action.add_anyway': 'Add Anyway',
    'feeds.import_curated.title': 'Import Curated Feeds',
    'feeds.import_curated.select': 'Select List',
    'feeds.import_curated.merge': 'Merge (Add New)',
    'feeds.import_curated.replace': 'Replace All',
  },
  'es': {
    'app.title': 'Personal News',
    'loading': 'Cargando...', 
    'search.placeholder': 'Buscar artículos...', 
    'search.results': 'Resultados para',
    'no.results': 'No se encontraron resultados',
    'read.more': 'Leer más',
    'published': 'Publicado el',
    'author': 'Por',
    'source': 'Fuente',
    'action.add': 'Añadir',
    'action.cancel': 'Cancelar',
    'action.save': 'Guardar',
    'action.delete': 'Eliminar',
    'action.edit': 'Editar',
    'action.refresh': 'Actualizar',
    'action.reset': 'Restablecer',
    'action.close': 'Cerrar',
    'action.back': 'Volver',
    'action.import': 'Importar',
    'action.export': 'Exportar',
    'action.remove': 'Quitar',
    'action.preview': 'Preview',
    'action.next': 'Siguiente',
    'action.prev': 'Anterior',
    'action.focus_mode': 'Modo Enfoque',
    'action.read': 'Leer',
    'action.read_article': 'Leer artículo',
    'time.now': 'ahora',
    'feeds.live': 'EN VIVO',
    'feeds.articles': 'artículos',
    'article.by': 'por',
    'article.end': 'Fin de edición',
    
    // Header
    'header.manage_feeds': 'Gestionar Feeds',
    'header.refresh': 'Actualizar Feeds',
    'header.settings': 'Ajustes',
    'header.favorites': 'Favoritos',
    'header.menu': 'Menú',
    'settings.title': 'Ajustes',
    'settings.language': 'Idioma',
    'settings.tab.appearance': 'Apariencia',
    'settings.tab.display': 'Visualización',
    'settings.tab.logs': 'Registros',
    'settings.tab.advanced': 'Avanzado',
    'settings.header.config': 'Configuración de Cabecera',
    'settings.header.title': 'Título',
    'settings.header.logo': 'Logo URL',
    'settings.header.upload': 'Subir',
    'settings.header.position': 'Posición',
    'settings.header.height': 'Altura',
    'settings.header.theme_color': 'Color del Tema',
    'settings.header.blur': 'Desenfoque',
    'settings.layout.preset': 'Preajuste de Diseño',
    'settings.colors': 'Colores',
    'settings.background': 'Fondo',
    'settings.display.options': 'Opciones de Visualización',
    'settings.display.top_stories': 'Historias Principales',
    'settings.display.auto_refresh': 'Actualización Auto',
    'settings.display.time_format': 'Formato de Hora',
    'settings.display.show_time': 'Mostrar Hora',
    'settings.system': 'Sistema',
    'settings.system.detect_theme': 'Tema Auto',
    'settings.system.transitions': 'Transiciones Suaves',
    'settings.backup': 'Copia de Seguridad',
    'settings.backup.desc': 'Exportar datos para migrar',
    'settings.reset.factory': 'Restablecer Fábrica',
    'settings.reset.desc': 'Restaurar valores visuales',
    'feeds.title': 'Gestionar Feeds',
    'feeds.tab.feeds': 'Feeds',
    'feeds.tab.categories': 'Categorías',
    'feeds.tab.analytics': 'Resumen',
    'feeds.add.placeholder': 'Introduce URL del sitio, RSS o YouTube...', 
    'feeds.import.lists': 'Importar Listas',
    'feeds.import.opml': 'Importar OPML',
    'feeds.stats.monitored': 'feeds monitoreados',
    'feeds.category.none': 'Sin categoría',
    'analytics.total_articles': 'Artículos en Caché',
    'analytics.updated': 'Actualizado',
    'analytics.health': 'Salud del Sistema',
    'analytics.operational': '100% Operativo',
    'analytics.issues': 'errores',
    'analytics.popular_topics': 'Temas Populares',
    'analytics.frequency': 'Mayor Frecuencia',
    'analytics.feed_status': 'Estado de Feeds',
    'analytics.attention': 'Requiere Atención',
    'analytics.valid': 'Válidos',
    'analytics.pending': 'Pendientes',
    'layout.grid': 'Revista',
    'layout.modern': 'Moderno',
    'layout.masonry': 'Mosaico',
    'layout.list': 'Lista',
    'layout.minimal': 'Minimalista',
    'layout.immersive': 'Inmersivo',
    'layout.timeline': 'Línea de Tiempo',
    'layout.bento': 'Bento',
    'layout.brutalist': 'Brutalista',
    'layout.newspaper': 'Periódico',
    'layout.focus': 'Enfoque',
    'layout.gallery': 'Galería',
    'layout.compact': 'Compacto',
    'layout.split': 'Dividido',
    'layout.cyberpunk': 'Cyberpunk',
    'layout.terminal': 'Terminal',
    'layout.pocketfeeds': 'PocketFeeds',
    'layout.default': 'Auto (Categoría)',
  },
  'fr': {
    'app.title': 'Personal News',
    'loading': 'Chargement...', 
    'search.placeholder': 'Rechercher...', 
    'search.results': 'Résultats pour',
    'no.results': 'Aucun résultat',
    'read.more': 'Lire la suite',
    'published': 'Publié le',
    'author': 'Par',
    'source': 'Source',
    'action.add': 'Ajouter',
    'action.cancel': 'Annuler',
    'action.save': 'Sauvegarder',
    'action.delete': 'Supprimer',
    'action.edit': 'Éditer',
    'action.refresh': 'Actualiser',
    'action.reset': 'Réinitialiser',
    'action.close': 'Fermer',
    'action.back': 'Retour',
    'action.import': 'Importer',
    'action.export': 'Exporter',
    'action.remove': 'Retirer',
    'action.preview': 'Preview',
    'action.next': 'Suivant',
    'action.prev': 'Précédent',
    'action.focus_mode': 'Mode Focus',
    
    // Header
    'header.manage_feeds': 'Gérer les Feeds',
    'header.refresh': 'Actualiser',
    'header.settings': 'Paramètres',
    'header.favorites': 'Favoris',
    'header.menu': 'Menu',
    'settings.title': 'Paramètres',
    'settings.language': 'Langue',
    'settings.tab.appearance': 'Apparence',
    'settings.tab.display': 'Affichage',
    'settings.tab.logs': 'Journaux',
    'settings.tab.advanced': 'Avancé',
    'settings.header.config': 'Configuration En-tête',
    'settings.header.title': 'Titre',
    'settings.header.logo': 'Logo URL',
    'settings.header.upload': 'Télécharger',
    'settings.header.position': 'Position',
    'settings.header.height': 'Hauteur',
    'settings.header.theme_color': 'Couleur Thème',
    'settings.header.blur': 'Flou',
    'settings.layout.preset': 'Préréglage',
    'settings.colors': 'Couleurs',
    'settings.background': 'Arrière-plan',
    'settings.display.options': 'Options d\'affichage',
    'settings.display.top_stories': 'À la une',
    'settings.display.auto_refresh': 'Rafraîchissement Auto',
    'settings.display.time_format': 'Format Heure',
    'settings.display.show_time': 'Afficher Heure',
    'settings.system': 'Système',
    'settings.system.detect_theme': 'Thème Auto',
    'settings.system.transitions': 'Transitions Douces',
    'settings.backup': 'Sauvegarde',
    'settings.backup.desc': 'Exporter pour migrer',
    'settings.reset.factory': 'Réinitialisation',
    'settings.reset.desc': 'Restaurer défauts visuels',
    'feeds.title': 'Gérer Feeds',
    'feeds.tab.feeds': 'Feeds',
    'feeds.tab.categories': 'Catégories',
    'feeds.tab.analytics': 'Aperçu',
    'feeds.add.placeholder': 'URL site, RSS ou YouTube...', 
    'feeds.import.lists': 'Importer Listes',
    'feeds.import.opml': 'Importer OPML',
    'feeds.stats.monitored': 'feeds suivis',
    'feeds.category.none': 'Non classé',
    'analytics.total_articles': 'Articles en Cache',
    'analytics.updated': 'Mis à jour',
    'analytics.health': 'Santé Système',
    'analytics.operational': '100% Opérationnel',
    'analytics.issues': 'erreurs',
    'analytics.popular_topics': 'Sujets Populaires',
    'analytics.frequency': 'Fréquence Top',
    'analytics.feed_status': 'État des Feeds',
    'analytics.attention': 'Attention Requise',
    'analytics.valid': 'Valides',
    'layout.grid': 'Magazine',
    'layout.modern': 'Moderne',
    'layout.masonry': 'Maçonnerie',
    'layout.list': 'Liste',
    'layout.minimal': 'Minimal',
    'layout.immersive': 'Immersif',
    'layout.timeline': 'Chronologie',
    'layout.bento': 'Bento',
    'layout.brutalist': 'Brutaliste',
    'layout.newspaper': 'Journal',
    'layout.focus': 'Focus',
    'layout.gallery': 'Galerie',
    'layout.compact': 'Compact',
    'layout.split': 'Divisé',
    'layout.cyberpunk': 'Cyberpunk',
    'layout.terminal': 'Terminal',
    'layout.pocketfeeds': 'PocketFeeds',
    'layout.default': 'Auto (Catégorie)',
  },
  'it': {
    'app.title': 'Personal News',
    'loading': 'Caricamento...', 
    'search.placeholder': 'Cerca articoli...', 
    'search.results': 'Risultati per',
    'no.results': 'Nessun risultato',
    'read.more': 'Leggi di più',
    'published': 'Pubblicato il',
    'author': 'Di',
    'source': 'Fonte',
    'action.add': 'Aggiungi',
    'action.cancel': 'Annulla',
    'action.save': 'Salva',
    'action.delete': 'Elimina',
    'action.edit': 'Modifica',
    'action.refresh': 'Aggiorna',
    'action.reset': 'Reimposta',
    'action.close': 'Chiudi',
    'action.back': 'Indietro',
    'action.import': 'Importa',
    'action.export': 'Esporta',
    'action.remove': 'Rimuovi',
    'action.preview': 'Preview',
    'action.next': 'Successivo',
    'action.prev': 'Precedente',
    'action.focus_mode': 'Modalità Focus',
    
    // Header
    'header.manage_feeds': 'Gestisci Feed',
    'header.refresh': 'Aggiorna Feed',
    'header.settings': 'Impostazioni',
    'header.favorites': 'Preferiti',
    'header.menu': 'Menu',
    'settings.title': 'Impostazioni',
    'settings.language': 'Lingua',
    'settings.tab.appearance': 'Aspetto',
    'settings.tab.display': 'Visualizzazione',
    'settings.tab.logs': 'Log',
    'settings.tab.advanced': 'Avanzate',
    'settings.header.config': 'Configurazione Intestazione',
    'settings.header.title': 'Titolo',
    'settings.header.logo': 'URL Logo',
    'settings.header.upload': 'Carica',
    'settings.header.position': 'Posizione',
    'settings.header.height': 'Altezza',
    'settings.header.theme_color': 'Colore Tema',
    'settings.header.blur': 'Sfocatura',
    'settings.layout.preset': 'Preset Layout',
    'settings.colors': 'Colori',
    'settings.background': 'Sfondo',
    'settings.display.options': 'Opzioni Visualizzazione',
    'settings.display.top_stories': 'Storie Principali',
    'settings.display.auto_refresh': 'Aggiornamento Auto',
    'settings.display.time_format': 'Formato Ora',
    'settings.display.show_time': 'Mostra Ora',
    'settings.system': 'Sistema',
    'settings.system.detect_theme': 'Tema Auto',
    'settings.system.transitions': 'Transizioni Fluide',
    'settings.backup': 'Backup & Dati',
    'settings.backup.desc': 'Esporta per migrazione',
    'settings.reset.factory': 'Reset Fabbrica',
    'settings.reset.desc': 'Ripristina default visivi',
    'feeds.title': 'Gestione Feed',
    'feeds.tab.feeds': 'Feed',
    'feeds.tab.categories': 'Categorie',
    'feeds.tab.analytics': 'Riepilogo',
    'feeds.add.placeholder': 'URL sito, RSS o YouTube...', 
    'feeds.import.lists': 'Importa Liste',
    'feeds.import.opml': 'Importa OPML',
    'feeds.stats.monitored': 'feed monitorati',
    'feeds.category.none': 'Senza categoria',
    'analytics.total_articles': 'Articoli in Cache',
    'analytics.updated': 'Aggiornato',
    'analytics.health': 'Salute Sistema',
    'analytics.operational': '100% Operativo',
    'analytics.issues': 'errori',
    'analytics.popular_topics': 'Argomenti Popolari',
    'analytics.frequency': 'Frequenza Top',
    'analytics.feed_status': 'Stato Feed',
    'analytics.attention': 'Richiede Attenzione',
    'analytics.valid': 'Validi',
    'analytics.pending': 'In attesa',
    'layout.grid': 'Rivista',
    'layout.modern': 'Moderno',
    'layout.masonry': 'Mosaico',
    'layout.list': 'Elenco',
    'layout.minimal': 'Minimale',
    'layout.immersive': 'Immersivo',
    'layout.timeline': 'Timeline',
    'layout.bento': 'Bento',
    'layout.brutalist': 'Brutalista',
    'layout.newspaper': 'Giornale',
    'layout.focus': 'Focus',
    'layout.gallery': 'Galleria',
    'layout.compact': 'Compatto',
    'layout.split': 'Diviso',
    'layout.cyberpunk': 'Cyberpunk',
    'layout.terminal': 'Terminale',
    'layout.pocketfeeds': 'PocketFeeds',
    'layout.default': 'Auto (Categoria)',
  },
  'zh': {
    'app.title': 'Personal News',
    'loading': '加载中...', 
    'search.placeholder': '搜索文章...', 
    'search.results': '结果',
    'no.results': '未找到结果',
    'read.more': '阅读更多',
    'published': '发布于',
    'author': '作者',
    'source': '来源',
    'action.add': '添加',
    'action.cancel': '取消',
    'action.save': '保存',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.refresh': '刷新',
    'action.reset': '重置',
    'action.close': '关闭',
    'action.back': '返回',
    'action.import': '导入',
    'action.export': '导出',
    'action.remove': '移除',
    'action.preview': 'Preview',
    'action.next': '下一个',
    'action.prev': '上一个',
    'action.focus_mode': '专注模式',
    
    // Header
    'header.manage_feeds': '管理 Feed',
    'header.refresh': '刷新 Feed',
    'header.settings': '设置',
    'header.favorites': '收藏',
    'header.menu': '菜单',
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.tab.appearance': '外观',
    'settings.tab.display': '显示',
    'settings.tab.logs': '日志',
    'settings.tab.advanced': '高级',
    'settings.header.config': '页眉配置',
    'settings.header.title': '标题',
    'settings.header.logo': 'Logo URL',
    'settings.header.upload': '上传',
    'settings.header.position': '位置',
    'settings.header.height': '高度',
    'settings.header.theme_color': '主题色',
    'settings.header.blur': '模糊',
    'settings.layout.preset': '布局预设',
    'settings.colors': '颜色',
    'settings.background': '背景',
    'settings.display.options': '显示选项',
    'settings.display.top_stories': '头条新闻',
    'settings.display.auto_refresh': '自动刷新',
    'settings.display.time_format': '时间格式',
    'settings.display.show_time': '显示时间',
    'settings.system': '系统',
    'settings.system.detect_theme': '自动主题',
    'settings.system.transitions': '平滑过渡',
    'settings.backup': '备份与数据',
    'settings.backup.desc': '导出数据以迁移设备',
    'settings.reset.factory': '恢复出厂',
    'settings.reset.desc': '恢复视觉默认值',
    'feeds.title': '管理 Feed',
    'feeds.tab.feeds': 'Feed',
    'feeds.tab.categories': '分类',
    'feeds.tab.analytics': '概览',
    'feeds.add.placeholder': '输入网站、RSS或YouTube地址...', 
    'feeds.import.lists': '导入列表',
    'feeds.import.opml': '导入OPML',
    'feeds.stats.monitored': '监控的订阅',
    'feeds.category.none': '未分类',
    'analytics.total_articles': '缓存文章',
    'analytics.updated': '已更新',
    'analytics.health': '系统健康',
    'analytics.operational': '100% 正常',
    'analytics.issues': '错误',
    'analytics.popular_topics': '热门话题',
    'analytics.frequency': '最高频率',
    'analytics.feed_status': '订阅状态',
    'analytics.attention': '需要注意',
    'analytics.valid': '有效',
    'analytics.pending': '待定',
    'layout.grid': '杂志',
    'layout.modern': '现代',
    'layout.masonry': '瀑布流',
    'layout.list': '列表',
    'layout.minimal': '极简',
    'layout.immersive': '沉浸式',
    'layout.timeline': '时间轴',
    'layout.bento': '便当盒',
    'layout.brutalist': '粗野主义',
    'layout.newspaper': '报纸',
    'layout.focus': '焦点',
    'layout.gallery': '画廊',
    'layout.compact': '紧凑',
    'layout.split': '分屏',
    'layout.cyberpunk': '赛博朋克',
    'layout.terminal': '终端',
    'layout.polaroid': '拍立得',
    'layout.default': '自动 (分类)',
  },
  'ja': {
    'app.title': 'Personal News',
    'loading': '読み込み中...', 
    'search.placeholder': '記事を検索...', 
    'search.results': '検索結果',
    'no.results': '結果が見つかりません',
    'read.more': '続きを読む',
    'published': '公開日',
    'author': '著者',
    'source': 'ソース',
    'action.add': '追加',
    'action.cancel': 'キャンセル',
    'action.save': '保存',
    'action.delete': '削除',
    'action.edit': '編集',
    'action.refresh': '更新',
    'action.reset': 'リセット',
    'action.close': '閉じる',
    'action.back': '戻る',
    'action.import': 'インポート',
    'action.export': 'エクスポート',
    'action.remove': '削除',
    'action.preview': 'Preview',
    'action.next': '次へ',
    'action.prev': '前へ',
    'action.focus_mode': 'フォーカスモード',
    
    // Header
    'header.manage_feeds': 'Feed管理',
    'header.refresh': 'Feed更新',
    'header.settings': '設定',
    'header.favorites': 'お気に入り',
    'header.menu': 'メニュー',
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.tab.appearance': '外観',
    'settings.tab.display': '表示',
    'settings.tab.logs': 'ログ',
    'settings.tab.advanced': '詳細',
    'settings.header.config': 'ヘッダー設定',
    'settings.header.title': 'タイトル',
    'settings.header.logo': 'ロゴURL',
    'settings.header.upload': 'アップロード',
    'settings.header.position': '位置',
    'settings.header.height': '高さ',
    'settings.header.theme_color': 'テーマ色',
    'settings.header.blur': 'ぼかし',
    'settings.layout.preset': 'レイアウトプリセット',
    'settings.colors': '色',
    'settings.background': '背景',
    'settings.display.options': '表示オプション',
    'settings.display.top_stories': 'トップ記事',
    'settings.display.auto_refresh': '自動更新',
    'settings.display.time_format': '時間形式',
    'settings.display.show_time': '時間を表示',
    'settings.system': 'システム',
    'settings.system.detect_theme': '自動テーマ',
    'settings.system.transitions': 'スムーズ遷移',
    'settings.backup': 'バックアップ',
    'settings.backup.desc': 'データのエクスポート',
    'settings.reset.factory': '初期化',
    'settings.reset.desc': '表示設定を戻す',
    'feeds.title': 'Feed管理',
    'feeds.tab.feeds': 'Feed',
    'feeds.tab.categories': 'カテゴリ',
    'feeds.tab.analytics': '概要',
    'feeds.add.placeholder': 'URL、RSS、YouTubeを入力...', 
    'feeds.import.lists': 'リスト導入',
    'feeds.import.opml': 'OPML導入',
    'feeds.stats.monitored': '監視中のフィード',
    'feeds.category.none': '未分類',
    'analytics.total_articles': 'キャッシュ記事',
    'analytics.updated': '更新',
    'analytics.health': 'システム状態',
    'analytics.operational': '100% 正常',
    'analytics.issues': 'エラー',
    'analytics.popular_topics': '人気トピック',
    'analytics.frequency': '高頻度',
    'analytics.feed_status': 'フィード状態',
    'analytics.attention': '要確認',
    'analytics.valid': '有効',
    'analytics.pending': '保留中',
    'layout.grid': 'マガジン',
    'layout.modern': 'モダン',
    'layout.masonry': 'メーソンリー',
    'layout.list': 'リスト',
    'layout.minimal': 'ミニマル',
    'layout.immersive': '没入型',
    'layout.timeline': 'タイムライン',
    'layout.bento': '弁当箱',
    'layout.brutalist': 'ブルータリスト',
    'layout.newspaper': '新聞',
    'layout.focus': 'フォーカス',
    'layout.gallery': 'ギャラリー',
    'layout.compact': 'コンパクト',
    'layout.split': '分割',
    'layout.cyberpunk': 'サイバーパンク',
    'layout.terminal': 'ターミナル',
    'layout.polaroid': 'ポラロイド',
    'layout.default': '自動 (カテゴリ)',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useLocalStorage<Language>('app-language', 'pt-BR');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
