import { useCallback } from 'react';
import { useLocalStorage } from './useLocalStorage';
import type { HeaderConfig, ContentConfig, LayoutPreset, BackgroundConfig } from '../types';
import { useExtendedTheme } from './useExtendedTheme';
import { DEFAULT_CONFIG } from '../services/auraWallpaperService';
import { BUILT_LAYOUT_PRESETS } from '../config/layoutPresets.config';
import { INITIAL_APP_CONFIG } from '../constants/curatedFeeds';
import { useLogger } from '../services/logger';
import { DEFAULT_HEADER_CONFIG, DEFAULT_CONTENT_CONFIG } from '../config/defaultConfig';

const defaultHeaderConfig: HeaderConfig = DEFAULT_HEADER_CONFIG;

const defaultContentConfig: ContentConfig = DEFAULT_CONTENT_CONFIG;

const defaultBackgroundConfig: BackgroundConfig = {
  type: 'aura',
  value: '', // Will be generated by BackgroundCreator
  auraSettings: DEFAULT_CONFIG,
};

// Layout presets agora vêm do arquivo de configuração centralizado
// Edite config/layoutPresets.config.ts para ajustar os presets
export const LAYOUT_PRESETS: LayoutPreset[] = BUILT_LAYOUT_PRESETS;

interface UserOverrides {
  header?: Partial<HeaderConfig>;
  content?: Partial<ContentConfig>;
}

export const useAppearance = () => {
  const logger = useLogger('useAppearance');
  const { themeSettings, updateThemeSettings, currentTheme, customThemes, defaultPresets, setCurrentTheme, removeCustomTheme } = useExtendedTheme();

  const [headerConfig, setHeaderConfig] = useLocalStorage<HeaderConfig>(
    'appearance-header',
    defaultHeaderConfig
  );

  const [contentConfig, setContentConfig] = useLocalStorage<ContentConfig>(
    'appearance-content',
    defaultContentConfig
  );

  const [backgroundConfig, setBackgroundConfig] = useLocalStorage<BackgroundConfig>(
    'appearance-background',
    defaultBackgroundConfig
  );

  const [activeLayoutId, setActiveLayoutId] = useLocalStorage<string | null>(
    'appearance-active-layout',
    INITIAL_APP_CONFIG.layout || 'modern'
  );

  // Store user manual overrides to ensure they take precedence over presets
  const [userOverrides, setUserOverrides] = useLocalStorage<UserOverrides>(
    'appearance-overrides',
    {}
  );

  const updateHeaderConfig = useCallback((updates: Partial<HeaderConfig>, persistOverride: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Header Update Call:', { updates, persistOverride });
    setHeaderConfig((prev) => ({ ...prev, ...updates }));
    if (persistOverride) {
      setActiveLayoutId(null);
      // Save manual override with safe merging
      setUserOverrides((prev) => {
        const currentOverrides = prev || {};
        return {
          ...currentOverrides,
          header: {
            ...(currentOverrides.header || {}),
            ...updates
          }
        };
      });
    }
  }, [setHeaderConfig, setUserOverrides, setActiveLayoutId, logger]);

  const updateContentConfig = useCallback((updates: Partial<ContentConfig>, persistOverride: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Content Update Call:', { updates, persistOverride });
    setContentConfig((prev) => ({ ...prev, ...updates }));
    if (persistOverride) {
      setActiveLayoutId(null);
      // Save manual override with safe merging
      setUserOverrides((prev) => {
        const currentOverrides = prev || {};
        return {
          ...currentOverrides,
          content: {
            ...(currentOverrides.content || {}),
            ...updates
          }
        };
      });
    }
  }, [setContentConfig, setUserOverrides, setActiveLayoutId, logger]);

  const updateBackgroundConfig = useCallback((updates: Partial<BackgroundConfig>) => {
    setBackgroundConfig((prev) => ({ ...prev, ...updates }));
  }, [setBackgroundConfig]);

  // Clear user overrides - useful for resetting to pure preset state
  const clearUserOverrides = useCallback(() => {
    setUserOverrides({});
  }, [setUserOverrides]);

  /**
   * Apply a layout preset.
   * 
   * IMPORTANT: As per user requirement, switching layouts should ONLY affect
   * the page content (below navigation), NOT the header configuration.
   * Header settings are managed separately in Settings.
   * 
   * @param presetId - ID of the layout preset to apply
   * @param persist - Whether to persist this as the active layout
   * @param clearContentOverrides - Whether to clear content overrides (default: true)
   */
  const applyLayoutPreset = useCallback((presetId: string, persist: boolean = true, clearContentOverrides: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Applying Layout Preset:', { presetId, persist });
    const preset = LAYOUT_PRESETS.find(p => p.id === presetId);
    if (preset) {
      // IMPORTANT: Preserve header overrides! User configured these in Settings.
      // Only clear content overrides to prevent layout settings from bleeding.
      if (clearContentOverrides) {
        setUserOverrides((prev) => ({
          ...prev,
          content: {} // Clear only content overrides, preserve header
        }));
      }

      // Apply content preset values
      // Content is the only thing that changes when switching layouts
      const contentOverrides = clearContentOverrides ? {} : (userOverrides?.content || {});

      const mergedContent = {
        ...defaultContentConfig,
        ...preset.content,
        ...contentOverrides
      };

      // Only update content, NOT header
      setContentConfig(mergedContent);

      if (persist) {
        setActiveLayoutId(presetId);
      }
    }
  }, [setContentConfig, setActiveLayoutId, userOverrides, setUserOverrides, logger]);

  const refreshAppearance = useCallback(() => {
    logger.debugTag('APPEARANCE', 'Refresh Triggered (Restoring State)');
    // Re-applies the current configuration based on active preset and user overrides.
    // Useful to clear temporary overrides (like category-specific headers).
    const headerOverrides = userOverrides?.header || {};
    const contentOverrides = userOverrides?.content || {};

    if (activeLayoutId) {
      const preset = LAYOUT_PRESETS.find(p => p.id === activeLayoutId);
      if (preset) {
        const mergedHeader = {
          ...defaultHeaderConfig,
          ...preset.header,
          ...headerOverrides
        };
        const mergedContent = {
          ...defaultContentConfig,
          ...preset.content,
          ...contentOverrides
        };
        setHeaderConfig(mergedHeader);
        setContentConfig(mergedContent);
        logger.debugTag('APPEARANCE', 'State Restored from Preset:', activeLayoutId);
        return;
      }
    }

    // Fallback or Custom mode: Just re-apply the current active layout if it exists
    // to clear temporary category-specific overrides.
    if (activeLayoutId) {
      applyLayoutPreset(activeLayoutId);
    }
  }, [activeLayoutId, applyLayoutPreset, setContentConfig, setHeaderConfig, userOverrides?.content, userOverrides?.header, logger]);

  const resetAppearance = useCallback(() => {
    setHeaderConfig(defaultHeaderConfig);
    setContentConfig(defaultContentConfig);
    setBackgroundConfig(defaultBackgroundConfig);
    setActiveLayoutId(null);
    setUserOverrides({}); // Clear overrides on reset
  }, [setHeaderConfig, setContentConfig, setBackgroundConfig, setActiveLayoutId, setUserOverrides]);

  return {
    headerConfig,
    contentConfig,
    backgroundConfig,
    activeLayoutId,
    updateHeaderConfig,
    updateContentConfig,
    updateBackgroundConfig,
    applyLayoutPreset,
    resetAppearance,
    clearUserOverrides,
    themeSettings,
    updateThemeSettings,
    currentTheme,
    customThemes,
    defaultPresets,
    setCurrentTheme,
    removeCustomTheme,
    refreshAppearance,
  };
};
