import { useCallback, useEffect } from 'react';
import { useLocalStorage } from './useLocalStorage';
import type { HeaderConfig, ContentConfig, LayoutPreset, BackgroundConfig } from '../types';
import { useExtendedTheme } from './useExtendedTheme';
import { DEFAULT_CONFIG } from '../services/auraWallpaperService';
import { BUILT_LAYOUT_PRESETS } from '../config/layoutPresets.config';
import { FEED_LAYOUT_IDS } from '../config/feedLayoutCatalog';
import { INITIAL_APP_CONFIG } from '../constants/curatedFeeds';
import { useLogger } from '../services/logger';
import { DEFAULT_HEADER_CONFIG, DEFAULT_CONTENT_CONFIG } from '../config/defaultConfig';
import { APP_BRAND_NAME } from '../config/brand';

const defaultHeaderConfig: HeaderConfig = DEFAULT_HEADER_CONFIG;

const defaultContentConfig: ContentConfig = DEFAULT_CONTENT_CONFIG;

const defaultBackgroundConfig: BackgroundConfig = {
  type: 'aura',
  value: '', // Will be generated by BackgroundCreator
  auraSettings: DEFAULT_CONFIG,
};

// Layout presets agora vêm do arquivo de configuração centralizado
// Edite config/layoutPresets.config.ts para ajustar os presets
export const LAYOUT_PRESETS: LayoutPreset[] = BUILT_LAYOUT_PRESETS;
const VALID_LAYOUT_IDS = new Set(LAYOUT_PRESETS.map((preset) => preset.id));
const VALID_LAYOUT_MODES = new Set<ContentConfig["layoutMode"]>([
  "default",
  ...FEED_LAYOUT_IDS,
]);
const MODERN_LAYOUT_ID = "modern";

interface UserOverrides {
  header?: Partial<HeaderConfig>;
  content?: Partial<ContentConfig>;
}

export const useAppearance = () => {
  const logger = useLogger('useAppearance');
  const { themeSettings, updateThemeSettings, currentTheme, customThemes, defaultPresets, setCurrentTheme, removeCustomTheme } = useExtendedTheme();

  const [headerConfig, setHeaderConfig] = useLocalStorage<HeaderConfig>(
    'appearance-header',
    defaultHeaderConfig
  );

  const [contentConfig, setContentConfig] = useLocalStorage<ContentConfig>(
    'appearance-content',
    defaultContentConfig
  );

  const [backgroundConfig, setBackgroundConfig] = useLocalStorage<BackgroundConfig>(
    'appearance-background',
    defaultBackgroundConfig
  );

  const [activeLayoutId, setActiveLayoutId] = useLocalStorage<string | null>(
    'appearance-active-layout',
    INITIAL_APP_CONFIG.layout || 'modern'
  );

  // Store user manual overrides to ensure they take precedence over presets
  const [userOverrides, setUserOverrides] = useLocalStorage<UserOverrides>(
    'appearance-overrides',
    {}
  );

  useEffect(() => {
    if (activeLayoutId && !VALID_LAYOUT_IDS.has(activeLayoutId)) {
      logger.warn("Invalid persisted layout detected, falling back to modern", {
        additionalData: { activeLayoutId },
      });
      setActiveLayoutId(MODERN_LAYOUT_ID);
    }
  }, [activeLayoutId, logger, setActiveLayoutId]);

  useEffect(() => {
    if (
      contentConfig.layoutMode &&
      !VALID_LAYOUT_MODES.has(contentConfig.layoutMode)
    ) {
      logger.warn("Invalid content layout detected, falling back to modern", {
        additionalData: { layoutMode: contentConfig.layoutMode },
      });
      setContentConfig((prev) => ({
        ...prev,
        layoutMode: MODERN_LAYOUT_ID as ContentConfig["layoutMode"],
      }));
    }
  }, [contentConfig.layoutMode, logger, setContentConfig]);

  useEffect(() => {
    const compactTitle = (headerConfig.customTitle || '')
      .trim()
      .toLowerCase()
      .replace(/\s+/g, '');
    const aliasTitles = new Set([
      '',
      'personalnews',
      'noticiaspessoais',
      'notíciaspessoais',
      'personalnewsrss',
    ]);

    if (!aliasTitles.has(compactTitle) || headerConfig.customTitle === APP_BRAND_NAME) {
      return;
    }

    logger.info('Normalizing persisted brand title to canonical app name', {
      additionalData: { previousTitle: headerConfig.customTitle },
    });

    setHeaderConfig((prev) => ({
      ...prev,
      customTitle: APP_BRAND_NAME,
    }));

    setUserOverrides((prev) => {
      if (!prev?.header) return prev;

      return {
        ...prev,
        header: {
          ...prev.header,
          customTitle: APP_BRAND_NAME,
        },
      };
    });
  }, [
    headerConfig.customTitle,
    logger,
    setHeaderConfig,
    setUserOverrides,
  ]);

  useEffect(() => {
    const hasDeprecatedHeaderControls = Boolean(
      headerConfig.logoUrl ||
      headerConfig.customLogoSvg ||
      headerConfig.logoColor ||
      headerConfig.logoColorMode ||
      headerConfig.syncFavicon !== undefined ||
      headerConfig.titleColor ||
      headerConfig.titleGradient ||
      headerConfig.useThemeColor !== undefined
    );

    if (!hasDeprecatedHeaderControls) {
      return;
    }

    logger.info("Removing deprecated header customization fields", {
      additionalData: {
        hasLogoUrl: Boolean(headerConfig.logoUrl),
        hasCustomLogoSvg: Boolean(headerConfig.customLogoSvg),
        hasTitleColor: Boolean(headerConfig.titleColor),
        hasTitleGradient: Boolean(headerConfig.titleGradient),
      },
    });

    setHeaderConfig((prev) => ({
      ...prev,
      logoUrl: null,
      customLogoSvg: undefined,
      logoColor: undefined,
      logoColorMode: undefined,
      syncFavicon: undefined,
      titleColor: undefined,
      titleGradient: undefined,
      useThemeColor: undefined,
    }));

    setUserOverrides((prev) => {
      if (!prev?.header) return prev;

      const {
        logoUrl: _logoUrl,
        customLogoSvg: _customLogoSvg,
        logoColor: _logoColor,
        logoColorMode: _logoColorMode,
        syncFavicon: _syncFavicon,
        titleColor: _titleColor,
        titleGradient: _titleGradient,
        useThemeColor: _useThemeColor,
        ...cleanHeaderOverrides
      } = prev.header;

      return {
        ...prev,
        header: cleanHeaderOverrides,
      };
    });
  }, [headerConfig, logger, setHeaderConfig, setUserOverrides]);

  const updateHeaderConfig = useCallback((updates: Partial<HeaderConfig>, persistOverride: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Header Update Call:', { updates, persistOverride });
    setHeaderConfig((prev) => ({ ...prev, ...updates }));
    if (persistOverride) {
      setActiveLayoutId(null);
      // Save manual override with safe merging
      setUserOverrides((prev) => {
        const currentOverrides = prev || {};
        return {
          ...currentOverrides,
          header: {
            ...(currentOverrides.header || {}),
            ...updates
          }
        };
      });
    }
  }, [setHeaderConfig, setUserOverrides, setActiveLayoutId, logger]);

  const updateContentConfig = useCallback((updates: Partial<ContentConfig>, persistOverride: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Content Update Call:', { updates, persistOverride });
    setContentConfig((prev) => ({ ...prev, ...updates }));
    if (persistOverride) {
      setActiveLayoutId(null);
      // Save manual override with safe merging
      setUserOverrides((prev) => {
        const currentOverrides = prev || {};
        return {
          ...currentOverrides,
          content: {
            ...(currentOverrides.content || {}),
            ...updates
          }
        };
      });
    }
  }, [setContentConfig, setUserOverrides, setActiveLayoutId, logger]);

  const updateBackgroundConfig = useCallback((updates: Partial<BackgroundConfig>) => {
    setBackgroundConfig((prev) => ({ ...prev, ...updates }));
  }, [setBackgroundConfig]);

  // Clear user overrides - useful for resetting to pure preset state
  const clearUserOverrides = useCallback(() => {
    setUserOverrides({});
  }, [setUserOverrides]);

  const getBaseAppearanceState = useCallback(() => {
    const headerOverrides = userOverrides?.header || {};
    const contentOverrides = userOverrides?.content || {};
    const preset = activeLayoutId
      ? LAYOUT_PRESETS.find((item) => item.id === activeLayoutId)
      : null;

    const mergedHeader = preset
      ? {
          ...defaultHeaderConfig,
          ...preset.header,
          ...headerOverrides,
        }
      : {
          ...defaultHeaderConfig,
          ...headerOverrides,
        };

    const mergedContent = preset
      ? {
          ...defaultContentConfig,
          ...preset.content,
          ...contentOverrides,
        }
      : {
          ...defaultContentConfig,
          ...contentOverrides,
        };

    return {
      header: mergedHeader,
      content: mergedContent,
    };
  }, [activeLayoutId, userOverrides?.content, userOverrides?.header]);

  const resolveBaseLayoutMode = useCallback(() => {
    const baseLayout = getBaseAppearanceState().content.layoutMode;
    if (baseLayout && baseLayout !== "default") {
      return baseLayout;
    }
    return INITIAL_APP_CONFIG.layout || MODERN_LAYOUT_ID;
  }, [getBaseAppearanceState]);

  /**
   * Apply a layout preset.
   * 
   * IMPORTANT: As per user requirement, switching layouts should ONLY affect
   * the page content (below navigation), NOT the header configuration.
   * Header settings are managed separately in Settings.
   * 
   * @param presetId - ID of the layout preset to apply
   * @param persist - Whether to persist this as the active layout
   * @param clearContentOverrides - Whether to clear content overrides (default: true)
   */
  const applyLayoutPreset = useCallback((presetId: string, persist: boolean = true, clearContentOverrides: boolean = true) => {
    logger.debugTag('APPEARANCE', 'Applying Layout Preset:', { presetId, persist });
    const preset = LAYOUT_PRESETS.find(p => p.id === presetId);
    if (preset) {
      // IMPORTANT: Preserve header overrides! User configured these in Settings.
      // Only clear content overrides to prevent layout settings from bleeding.
      if (clearContentOverrides) {
        setUserOverrides((prev) => ({
          ...prev,
          content: {} // Clear only content overrides, preserve header
        }));
      }

      // Apply content preset values
      // Content is the only thing that changes when switching layouts
      const contentOverrides = clearContentOverrides ? {} : (userOverrides?.content || {});

      const mergedContent = {
        ...defaultContentConfig,
        ...preset.content,
        ...contentOverrides
      };

      // Only update content, NOT header
      setContentConfig(mergedContent);

      if (persist) {
        setActiveLayoutId(presetId);
      }
    }
  }, [setContentConfig, setActiveLayoutId, userOverrides, setUserOverrides, logger]);

  const refreshAppearance = useCallback(() => {
    logger.debugTag('APPEARANCE', 'Refresh Triggered (Restoring State)');
    const restoredState = getBaseAppearanceState();
    setHeaderConfig(restoredState.header);
    setContentConfig(restoredState.content);

    logger.debugTag('APPEARANCE', 'State restored from base appearance', {
      activeLayoutId,
      layoutMode: restoredState.content.layoutMode,
    });
  }, [activeLayoutId, getBaseAppearanceState, setContentConfig, setHeaderConfig, logger]);

  const resetAppearance = useCallback(() => {
    setHeaderConfig(defaultHeaderConfig);
    setContentConfig(defaultContentConfig);
    setBackgroundConfig(defaultBackgroundConfig);
    setActiveLayoutId(null);
    setUserOverrides({}); // Clear overrides on reset
  }, [setHeaderConfig, setContentConfig, setBackgroundConfig, setActiveLayoutId, setUserOverrides]);

  return {
    headerConfig,
    contentConfig,
    backgroundConfig,
    activeLayoutId,
    updateHeaderConfig,
    updateContentConfig,
    updateBackgroundConfig,
    applyLayoutPreset,
    resetAppearance,
    clearUserOverrides,
    themeSettings,
    updateThemeSettings,
    currentTheme,
    customThemes,
    defaultPresets,
    setCurrentTheme,
    removeCustomTheme,
    refreshAppearance,
    resolveBaseLayoutMode,
  };
};
