[[permission]]
identifier = "allow-set-window-style"
description = "Permite alterar o estilo da janela"
commands.allow = [
  "set_window_style"
]

[[permission]]
identifier = "allow-open-external-url"
description = "Permite abrir URLs externas"
commands.allow = [
  "open_external_url"
]
